### ISSUE TITLE
Can't get SID

### ISSUE THREAD

**Issue by FrancescoTalotta** [cardigliano/wireshark-fritzbox#3]
Hello,

I tested your script, however I am unable to get a SID on my FritzBox 7590 running fritzos 7.50 

Do you have any idea on how to get a SID? 

Thank you

**Comment by meiser79** [comment]
Hi, please find attached my modification to get it working.

[wireshark-fritzbox.patch.txt](https://github.com/cardigliano/wireshark-fritzbox/files/11074789/wireshark-fritzbox.patch.txt)

**Comment by cardigliano** [comment]
@meiser79 could you send a PR please?
